// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc4oilYN05pLL2WJ4iGfRU95dvXUorCwM',
    appId: '1:403318644220:web:9d75c4eaa1e58c2933e679',
    messagingSenderId: '403318644220',
    projectId: 'muhasebeyeni-d4f17',
    authDomain: 'muhasebeyeni-d4f17.firebaseapp.com',
    storageBucket: 'muhasebeyeni-d4f17.appspot.com',
    measurementId: 'G-S2BJQ487GB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwzIk_2FxHHcO0Jz2bcDJkMYsewmJdu8o',
    appId: '1:403318644220:android:54a3b01fcb79876133e679',
    messagingSenderId: '403318644220',
    projectId: 'muhasebeyeni-d4f17',
    storageBucket: 'muhasebeyeni-d4f17.appspot.com',
  );
}
